stages:
  - dependencies: ["init"]
    name: generation_madgraph_pythia
    scheduler:
      parameters:
        ma5_recast_card:
          output: ma5_recast_card
          step: init
        ma5_recast_card:
          output: ma5_recast_card
          step: init
        ma5_run_card:
          output: ma5_run_card
          step: init
        param_card:
          output: param_card
          step: init
        proc_card:
          output: proc_card
          step: init
        run_card:
          output: run_card
          step: init
        ufotar:
          output: ufotar
          step: init
        n_events: 10000
        param_card: {stages: init, output: param_cards, flatten: true}
      scheduler_type: multistep-stage
      scatter:
        method: zip
        parameters: ['param_card']
      workflow: { $ref : 'ma5.yaml'}